steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sales-ai-491622/scout-slack:latest', '-f', 'Dockerfile.slack', '.']
images:
- 'gcr.io/sales-ai-491622/scout-slack:latest'
